spring:
  elasticsearch:
    username: elastic
    password: elastic
    uris: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/livid?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql